### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by moulai**
## :bird: Purpose of this PR :bird:

The last [Dockerfile](https://github.com/magpiemodel/magpie/blob/master/Dockerfile) update was **two years** ago. In the past two years, MAgPIE has undergone numerous updates and its reliance on the environment has also changed. This old version of the Dockerfile is **currently unusable** (can't successfully run MAgPIE after building and running the docker image).

Docker is the easiest way to run MAgPIE on a new machine. At the same time, it also enables the beginners of the MAgPIE to avoid the trouble of cumbersome environment configuration, and can concentrate on the learning and setting of the model itself.

I made **an update to the Dockerfile**. I have tested it to be able to run the default configuration and generate the validation.pdf successfully.

The updated details are as follows:
1. Update the version of R to **4.2.1**.
2. Added missing software such as `proj`, `gdal`, `git` and some libs to the `apt-get install` list.
3. Update the packages that R needs to install to be consistent with the latest instructions in [README.md](https://github.com/magpiemodel/magpie/blob/master/README.md).
4. Installed missing R packages, such as `ncdf4`, `raster`, etc.
5. Replace the constants in the download and installation paths of GAMS with environment variables.
6. Update the version of GAMS to **40.2**.
    The version of GAMS can be easily changed by editing `LATEST` and `LATEST_SHORT` in the Dockerfile.
    As stated in [README.md](https://github.com/magpiemodel/magpie/blob/master/README.md):
    > "As the model benefits significantly of recent improvements in GAMS and CONOPT4 it is recommended to work with the most recent versions of both".

Note, as of September 2022, the latest GAMS version is 40.3, but this version has not been tested. It has been tested that MAgPIE works fine with GAMS 40.2.

@tscheypidi @giannou @pfuehrlich-pik 

## :wrench: Checklist for PR creator :wrench:

- [ ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [x] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * No performance loss/gain.

- [ ] Added changes to `CHANGELOG.md`
  * I think modifying `CHANGELOG.md` is better done by the MAgPIE team.
  * Here is a possible change log for reference: `**main** Update Dockerfile for running MAgPIE in a container`

- [x] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [x] No hard coded numbers and cluster/country/region names.
- [x] The new code doesn't contain declared but unused parameters or variables.
- [x] Where relevant, In-code comments added including documentation comments.
- [x] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [x] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
  * No need.

- [x] Self-review of my own code.
- [x] In case of updated cellular input tgz file in default.cfg: scenario_config.csv has been updated accordingly (rcp1p9, rcp2p6 etc)
  * No need.

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

### CODE REVIEW

**Review by tscheypidi — APPROVED** [review]
looks good. Thanks @moulai for fixing it! Much appreciated!

**Review by tscheypidi — APPROVED** [review]

**Comment by tscheypidi** [comment]
one note: we will merge that into the develop branch and it will be deployed to master with our next official release

**Review by pfuehrlich-pik — APPROVED** [review]

**Comment by moulai** [comment]
Thank you for your reply and approval!
